[package]
name = "bloq_vm"
version.workspace = true
description = "Execute Bloq IR with ticit."
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
bloq_circuit.workspace = true
bloq_ir.workspace = true
glam.workspace = true
rand.workspace = true
rustc-hash.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
ticit.workspace = true

[dev-dependencies]
bloq_compile.workspace = true
bloq_graph = { workspace = true, features = ["verify"] }
bloq_stim = { path = "../bloq_stim", features = ["verify"] }
bloq_test.workspace = true
quizx.workspace = true
rstest.workspace = true
stim.workspace = true

[lints]
workspace = true
