"""Compiled-program inspection types and exchange-format constants.

Use these types when inspecting a `bloq.Bloq`, matching node or circuit variants,
or writing a custom backend. They are the same native objects returned by program
accessors; importing this namespace adds no wrappers or conversions.

Examples:
    >>> import bloq
    >>> from bloq.ir import CircuitOp, RegionKind
    >>> program = bloq.compile(bloq.GalleryItem.X_MEMORY.load(), distance=3)
    >>> isinstance(program.template(0).circuit.ops()[0], CircuitOp)
    True
    >>> program.regions_of(RegionKind.RepeatUntilSuccess)
    []
"""

from bloq._core import (
    BLOQ_BINARY_EXTENSION,
    BLOQ_BINARY_VERSION,
    BLOQ_TEXT_EXTENSION,
    BLOQ_TEXT_VERSION,
    BloqEdge,
    BloqEdgeRef,
    BloqNode,
    BloqNodeKind,
    BloqStats,
    BoundaryFace,
    BoundaryFlow,
    BundleDetector,
    BundleDetectorTerm,
    CLIFFORD_PROXY_SEED_METADATA_KEY,
    CODE_DISTANCE_METADATA_KEY,
    CONVENTION_METADATA_KEY,
    Circuit,
    CircuitOp,
    ClassicalExpr,
    ClassicalNode,
    ClassicalResolution,
    ConditionalCorrection,
    DetectorBundle,
    DetectorBundleUse,
    DetectorTerm,
    EmissionPlan,
    ExpandedMeasurementColumns,
    FramePair,
    InstanceBoundaryOperator,
    InstanceMeasurement,
    InstanceProvenance,
    LogicalOutput,
    MemoryRoundTarget,
    NodeDetector,
    NodeKey,
    NodeParity,
    NodeProvenance,
    NodeRestart,
    ObservableOutput,
    PipePadding,
    PipeSeam,
    QuantumGuard,
    QuantumNode,
    RegionKind,
    RegionNode,
    RegionRef,
    SubGraph,
    Template,
    TemplateDetector,
    TemplateInstance,
    TemplateParity,
    TemplateRepeatState,
    TemplateRestart,
    TemporalPipe,
    ValueInput,
    ValueRef,
    ValueRole,
    WalkNode,
)

__all__ = [
    "BLOQ_BINARY_EXTENSION",
    "BLOQ_BINARY_VERSION",
    "BLOQ_TEXT_EXTENSION",
    "BLOQ_TEXT_VERSION",
    "BloqEdge",
    "BloqEdgeRef",
    "BloqNode",
    "BloqNodeKind",
    "BloqStats",
    "BoundaryFace",
    "BoundaryFlow",
    "BundleDetector",
    "BundleDetectorTerm",
    "CLIFFORD_PROXY_SEED_METADATA_KEY",
    "CODE_DISTANCE_METADATA_KEY",
    "CONVENTION_METADATA_KEY",
    "Circuit",
    "CircuitOp",
    "ClassicalExpr",
    "ClassicalNode",
    "ClassicalResolution",
    "ConditionalCorrection",
    "DetectorBundle",
    "DetectorBundleUse",
    "DetectorTerm",
    "EmissionPlan",
    "ExpandedMeasurementColumns",
    "FramePair",
    "InstanceBoundaryOperator",
    "InstanceMeasurement",
    "InstanceProvenance",
    "LogicalOutput",
    "MemoryRoundTarget",
    "NodeDetector",
    "NodeKey",
    "NodeParity",
    "NodeProvenance",
    "NodeRestart",
    "ObservableOutput",
    "PipePadding",
    "PipeSeam",
    "QuantumGuard",
    "QuantumNode",
    "RegionKind",
    "RegionNode",
    "RegionRef",
    "SubGraph",
    "Template",
    "TemplateDetector",
    "TemplateInstance",
    "TemplateParity",
    "TemplateRepeatState",
    "TemplateRestart",
    "TemporalPipe",
    "ValueInput",
    "ValueRef",
    "ValueRole",
    "WalkNode",
]
