#!/usr/bin/env python3
"""Regenerate distribution notices from fetched, locked Cargo sources (Python 3.11+)."""

import argparse
import hashlib
import json
from pathlib import Path
import subprocess


ROOT = Path(__file__).resolve().parents[1]
OUTPUTS = (ROOT / "THIRD-PARTY-NOTICES.txt", ROOT / "bloq_py/THIRD-PARTY-NOTICES.txt")


def notice_files(root):
    """Include nested native-library and font notices, not just crate licenses."""
    return sorted(
        path for path in root.rglob("*")
        if path.is_file()
        and path.suffix not in (".rs", ".html", ".json")
        and (
            path.name.lower().startswith(("license", "licence", "copyright", "notice", "copying"))
            or (path.suffix in (".md", ".txt") and "license" in path.name.lower())
            or path.name in ("OFL.txt", "UFL.txt", "Hack-Regular.txt")
        )
    )


def render(packages, supplemental):
    texts = {}
    inventory = []
    for package in sorted(packages, key=lambda item: (item["name"], item["version"])):
        if not package["source"]:
            continue
        key = f"{package['name']}@{package['version']}"
        root = Path(package["manifest_path"]).parent
        if not Path(package["manifest_path"]).is_file():
            raise ValueError(f"Missing crate source for {key}; run cargo fetch --locked")
        entries = [
            {"source": f"{key}/{path.relative_to(root).as_posix()}",
             "text": path.read_text(encoding="utf-8")}
            for path in notice_files(root)
        ]
        entries.extend(entry for entry in supplemental if key in entry["packages"])
        if not entries:
            raise ValueError(f"Missing license text for {key}; add verified upstream notices")
        inventory.extend((f"\n{key}", f"Declared license: {package['license']}"))
        if package["authors"]:
            inventory.append("Declared authors: " + "; ".join(package["authors"]))
        for entry in entries:
            content = "\n".join(line.rstrip() for line in entry["text"].strip().splitlines()) + "\n"
            identifier = hashlib.sha256(content.encode()).hexdigest()
            texts[identifier] = content
            inventory.append(f"  [{identifier}] {entry['source']}")
    header = (
        "Bloq third-party notices\n"
        "========================\n\n"
        "Generated by tools/third_party_licenses.py from Cargo.lock and verified\n"
        "supplemental notices. This inventory covers workspace dependencies across\n"
        "platforms, optional features, and build/test tools; each distribution uses\n"
        "a subset. License expressions and authors are copied from crate metadata.\n"
        "Repeated license texts are included once and referenced by SHA-256.\n"
        "Bloq's separately bundled editor fonts have accompanying font notices.\n"
    )
    sections = [f"\n\n--- {key} ---\n\n{value}" for key, value in sorted(texts.items())]
    return header + "\n".join(inventory) + "".join(sections)


def check_selection():
    """Guard inclusion of vendored code/fonts and rejection of missing notices."""
    import tempfile

    with tempfile.TemporaryDirectory() as directory:
        root = Path(directory)
        for name in ("LICENSE", "vendor/stim/LICENSE", "fonts/OFL.txt", "fonts/UFL.txt"):
            file = root / name
            file.parent.mkdir(parents=True, exist_ok=True)
            file.write_text("a license\n", encoding="utf-8")
        package = dict(name="example", version="1", source="registry", license="MIT",
                       authors=["Example author"], manifest_path=str(root / "Cargo.toml"))
        (root / "Cargo.toml").touch()
        output = render([package], [])
        assert "example@1/vendor/stim/LICENSE" in output
        assert "example@1/fonts/OFL.txt" in output and "example@1/fonts/UFL.txt" in output
        assert output.count("a license\n") == 1
        assert directory not in output
        for file in notice_files(root):
            file.unlink()
        try:
            render([package], [])
        except ValueError:
            pass
        else:
            raise AssertionError("missing notices must fail")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if committed notices are stale")
    args = parser.parse_args()
    check_selection()
    metadata = json.loads(subprocess.check_output(
        ["cargo", "metadata", "--locked", "--offline", "--all-features", "--format-version", "1"],
        cwd=ROOT, text=True,
    ))
    supplemental = json.loads(Path(__file__).with_suffix(".json").read_text(encoding="utf-8"))
    output = render(metadata["packages"], supplemental)
    for path in OUTPUTS:
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != output:
                raise SystemExit(
                    f"Stale {path.relative_to(ROOT)}; run uv run --no-project python tools/third_party_licenses.py"
                )
        else:
            path.write_text(output, encoding="utf-8")
    print("Third-party notices checked" if args.check else "Third-party notices generated")


if __name__ == "__main__":
    main()
